

langText = { 
	"html_title": "add one", 
	"c_all": "All" ,
	"c_toprocess":"ToProcess",
	"c_topublish":"ToPublish",
	"c_unqualified":"unqualified",
	"c_todiagnoise":"ToDiagnoise",
	"c_return":"Back",
	"c_diagnoised":"diagnoised",
	"c_finished":"finished",
	"c_evaluated":"evaluated",
	
	"tableheader_status":"status",
	"tableheader_samplenum":"Sample No.",
	"tableheader_patientname":"Patient name",
	"tableheader_patientage":"patient age",
	"tableheader_sickpart":"Sampling sites",
	"tableheader_hospname":"Hospital",
	"tableheader_testdate":"Testdate",
	"tableheader_enddate":"Enddate",	
	"btn_feedback":"feedback",
	"btn_diagnose":"Diagnostic",
	"btn_checkreason":"checkreason",
	"btn_errorreason":"Error reason",
	"btn_backreason":"Return Reason",
	"btn_unqualified":"Unqualified",
	"btn_qualified":"Qualified",
	"btn_setexperter":"Set Expert",
	"btn_reassign":"Reassign",
	"btn_backassign":"Return assign",
	"btn_summary":"Summary",	
	"btn_userfeedback":"User feedback",
	"btn_back":"Return",
	"btn_readfinished":"Finishe",
	"btn_usercenter":"UserCenter",
	"btn_quit":"Quit",
	"logintitle":"Sys login",
	"systitle":"医云远程病理平台",
	"btn_forgotpwd":"forgot password",
	"btn_login":"Login",
	"editBtn":"Edit",
	"btn_return":"Close",
	"btn_unqualify":"Unqualified",
	"btn_qualify":"Qualified",
	"lbl_samplenum":"Samples No.：",
	"lbl_testdate":"Test Date：",
	"lbl_patientname":"Patient Name：",
	"lbl_certificateno":"ID No.：",
	"lbl_patientsex":"Patient Gender：",
	"lbl_patientage":"Patient Age：",
	"lbl_patientphone":"Patient Tel.：",
	"lbl_sickpart":"Sampling sites：",
	"lbl_hospname":"Hospital：",
	"lbl_clinicaldiagnosis":"Clinical diagnosis：",
	"lbl_hospcontacts":"Doctor：",
	"lbl_hospphone":"Doctor's phone：",
	"lbl_operationfindings":"Surgical findings：",
	"lbl_macroscopicdesc":"Gross Inspection：",
	"lbl_lastdiagnoseinfo":"Original Diagnosis：",
	"lbl_patientsexage":"Gender/Age",
	"lbl_diagnoseresult":"Diagnose Result：",
	"lbl_diagy":"History：",	
	"lbl_remark":"Notes：",
	"btn_ok":"OK",
	"btn_cancel":"Cancel",
	"mark_ok":"mark ok！"
};
