
langText = { 
	"html_title": "病例清单", 
	"c_all": "全部" ,
	"c_toprocess":"待处理",
	"c_topublish":"待发布",
	"c_unqualified":"不合格",
	"c_todiagnoise":"待阅片",
	"c_return":"退回",
	"c_diagnoised":"已阅片",
	"c_finished":"已完成",
	"c_evaluated":"已评价",	
	"tableheader_status":"状态",
	"tableheader_samplenum":"标本号",
	"tableheader_patientname":"病人姓名",
	"tableheader_patientage":"病人年龄",
	"tableheader_sickpart":"取材部位",
	"tableheader_hospname":"申请医院",
	"tableheader_testdate":"送检日期",
	"tableheader_enddate":"截止日期",	
	"btn_feedback":"评价",
	"btn_diagnose":"诊断建议",
	"btn_checkreason":"查看原因",
	"btn_errorreason":"错误原因",
	"btn_backreason":"退回原因",
	"btn_unqualified":"不合格",
	"btn_qualified":"合格",
	"btn_setexperter":"分配专家",
	"btn_reassign":"补充发布",
	"btn_backassign":"退回发布",
	"btn_summary":"综合处理",	
	"btn_userfeedback":"用户评价",
	"btn_back":"退回",
	"btn_readfinished":"阅片完成",
	"btn_usercenter":"用户中心",
	"btn_quit":"退出系统",
	"logintitle":"病理平台登录",
	"systitle":"医云远程病理平台",
	"btn_forgotpwd":"忘记密码",
	"btn_login":"登  录",	
	"editBtn":"编辑",
	"btn_return":"关闭",
	"btn_unqualify":"不合格",
	"btn_qualify":"合格",
	"lbl_samplenum":"标本号码：",
	"lbl_testdate":"送检日期：",
	"lbl_patientname":"患者姓名：",
	"lbl_certificateno":"证件号码：",
	"lbl_patientsex":"病人性别：",
	"lbl_patientage":"病人年龄：",
	"lbl_patientphone":"患者联系电话：",
	"lbl_sickpart":"取材部位：",
	"lbl_hospname":"送检医院：",
	"lbl_clinicaldiagnosis":"临床诊断：",
	"lbl_hospcontacts":"送检医生：",
	"lbl_hospphone":"送检医生电话：",
	"lbl_operationfindings":"手术所见：",
	"lbl_macroscopicdesc":"巨检描述：",
	"lbl_lastdiagnoseinfo":"原单位病理诊断：",
	"lbl_patientsexage":"性别/年龄",
	"lbl_diagnoseresult":"诊断结果：",
	"lbl_diagy":"病史：",	
	"lbl_remark":"备注：",
	"btn_ok":"确认",
	"btn_cancel":"取 消",
	"mark_ok":"标注成功！"
}
